import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const envPath = join(rootDir, '.env');
const outputPath = join(rootDir, 'src', 'config-generated.ts');

function generateConfig() {
  let customServerUrl = '';

  try {
    const envContent = readFileSync(envPath, 'utf-8');
    const match = envContent.match(/CUSTOME_SKILLS_SERVER_BASE_URL=(.+)/);
    if (match) {
      customServerUrl = match[1].trim();
    }
  } catch {
    // .env not found, use empty string
  }

  const configContent = `// Auto-generated by scripts/generate-config.ts
// Do not edit manually

export const CUSTOM_SKILLS_SERVER_BASE_URL = ${JSON.stringify(customServerUrl)};
`;

  writeFileSync(outputPath, configContent, 'utf-8');
  console.log(`Generated config: ${outputPath}`);
  if (customServerUrl) {
    console.log(`Custom skills server: ${customServerUrl}`);
  }
}

generateConfig();
